<?php
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="products" ng-controller="ProductsCtrl" ng-init="init('<?php echo $this->escapeHtml($list_type);?>',<?php echo $this->escapeHtml($list_id);?>)">
    <ul class="thumbnails">
        <li class="span2">
            <div class="thumbnail">
                <img src="http://www.ikea.com/PIAimages/16032_PE100309_S3.jpg" alt="">
                <h3><strong>{{title}}</strong> labels asdf</h3>
                <p>Thumbnail caption...({{list_type}})</p>
                <p>Thumbnail caption...({{list_id}})</p>
            </div>
        </li>
        ...
    </ul>
</div>