<div style="margin: 0 auto; max-width: 400px">
    <h1>Вход в систему</h1>

    <form role="form">
        <div class="form-group">
            <label for="exampleInputEmail1">Електронная почта</label>
            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Пароль</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <div class="checkbox">
            <label>
                <input type="checkbox"> Оставатся в системе
            </label>
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</div>