<h1> Корзина покупок</h1>
<div class="cart_table" data-ng-controller="ShoppingCart">
    <div class="modal my-modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Modal title</h4>
                </div>
                <div class="modal-body">
                    <img id="big_img" src="">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
<!--                    <button type="button" class="btn btn-primary">Save changes</button>-->
                </div>
            </div>
        </div>
    </div>
    <table class="table table-hover">
        <tr>
            <th>#</th>
            <th>Товар</th>
            <th>Количество</th>
            <th>Общая цена</th>
            <th></th>
        </tr>
        <tr data-ng-repeat="product in data">
            <td>{{$index+1}}</td>
            <td>
                <div>
                    <div class="card_product">
                        <div>
                            <img class="img-thumbnail cart-img" src="{{img(product.item.img)}}" data-ng-click="showImg(product.item)">
                        </div>
                        <div class="cart-info">
                            <a ng-href="/category/product/{{product.item.id}}">
                                <div><strong>{{product.item.title}}</strong></div>
                                <div><em>{{product.item.desp}}</em></div>
                            </a>
                        </div>
                    </div>
                </div>
            </td>
            <td>
                <input type="number" class="form-control" min=1 max=99 ng-model="product.number" ng-change="numChange(product)">
            </td>
            <td><strong class="price">{{product.number*product.item.price}} грн</strong></td>
            <td><button class="btn btn-danger btn-xs" data-ng-click="remove(product, $event)"><span class="glyphicon glyphicon-remove"></span></button></td>
        </tr>
    </table>
    <h3 class="sum">Сумма: {{price()}} грн</h3>
    <button type="button" class="btn btn-info right">Зделать заказ</button>
</div>