<div style="margin: 0 auto; max-width: 500px" ng-controller="UserCtrl">
    <h1>Мои данные:</h1>

    <form role="form">
        <div class="form-group">
            <label for="email">Електронная почта</label>
            <input type="email" ng-model="user.email" name="email" class="form-control" id="email" placeholder="введите электронную почту">
        </div>
        <div class="form-group">
            <label for="fullName">Имя, фамилия:</label>
            <input type="text" ng-model="user.fullName"  name="fullName" class="form-control" id="fullName" placeholder="Имя, фамилия">
        </div>
        <div class="form-group">
            <label for="phone">контактный телефон:</label>
            <input type="text" ng-model="user.phone" name="phone" class="form-control" id="phone" placeholder="контактный телефон">
        </div>
        <div class="form-group">
            <label for="location">Адрес доставки:</label>
            <textarea name="location" ng-model="user.location"  class="form-control" id="location" placeholder="Адрес доставки"></textarea>
        </div>
        <div class="form-group">
            <label for="otherInfo">Ваши пожелания:</label>
            <textarea name="otherInfo" ng-model="user.otherInfo" class="form-control" id="otherInfo" placeholder="Ваши пожелания"></textarea>
        </div>
        <button type="submit" class="btn btn-success pull-right" ng-click="submit()">Заказать</button>
        <span class="help-block" style="opacity: 0">some text </span>
    </form>
</div>