<?php
$this->headTitle($title);
//var_dump($products);
?>
<div class="products-list" ng-controller="ProductsListCtrl">
<div class="panel panel-primary" ng-repeat="product in products">
    <div class="panel-heading">{{product[0].header}}</div>
    <div class="panel-body">
        <div class="list-group">
            <a href="#" class="list-group-item" ng-repeat="item in product">{{item.value}}</a>
        </div>
    </div>
</div>
</div>
