<div id="main-carousel" class="carousel slide main-carousel" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#main-carousel" data-slide-to="0" class="active"></li>
        <li data-target="#main-carousel" data-slide-to="1"></li>
        <li data-target="#main-carousel" data-slide-to="2"></li>
        <li data-target="#main-carousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <img src="http://www.ikea.com/ms/pl_PL/img/vitality/sypialnia_luty/ziewamy_1060x415_v1.jpg" alt="picture 1">

            <div class="carousel-caption">
                <h2>Some text </h2>
            </div>
        </div>
        <div class="item">
            <img
                src="http://www.ikea.com/ms/pl_PL/img/vitality/homepage/seo_image/materace__fizjoterapeuci_1060x415.jpg"
                alt="picture 1">

            <div class="carousel-caption">
                <h2>Some text for second picture</h2>
            </div>
        </div>
        <div class="item">
            <img src="http://www.ikea.com/ms/pl_PL/img/vitality/homepage/upleva_1060x415.jpg" alt="picture 1">

            <div class="carousel-caption">
                <h2>Lorem ipsum</h2>
            </div>
        </div>
        <div class="item">
            <img src="http://www.ikea.com/ms/pl_PL/img/vitality/homepage/transport_materaca_z_domu_1060x415.jpg"
                 alt="picture 1">

            <div class="carousel-caption">
                <div class="carousel-caption">
                    <h2>1 000 000 $</h2>
                </div>
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#main-carousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#main-carousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>

<h1>Lorem ipsum</h1>
<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore
    magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
    gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing
    elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero
    eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum
    dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
    labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.
    Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>

<p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat
    nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue
    duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy
    nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>